//! Running the two binaries over a stratified grid and collecting IMs.
//!
//! # Why the grid is stratified rather than seed-only
//!
//! The obvious design is "resample the same fault with different seeds". That
//! holds the geometry fixed, which makes it blind to any error that depends on
//! distance or take-off angle — and that is precisely where the ray tracing, the
//! site amplification and the path-duration table live. A bug in `geom_terms`'
//! path accumulation would be invisible at one station and obvious at six.
//!
//! So the grid is **fault × station distance × seed**, with the distances chosen
//! to straddle the `ipdur_model = 11` path-duration breakpoints at 7, 45, 125 and
//! 175 km. Each of those is a discontinuity in the model; sampling only between
//! them would leave the branch selection untested.
//!
//! # Determinism
//!
//! The seed list is a fixed arithmetic sequence, not drawn at random. The whole
//! campaign is therefore reproducible from the two binaries alone — a statistical
//! gate with no flakiness, which is what makes it safe to set a tight band.

use im::Measures;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// First seed, and the stride between them.
///
/// Coprime-ish stride so successive seeds are not close: `init_random_seed` folds
/// `irand, irand+1, ...` into the generator state, and near-identical seeds could
/// in principle give correlated streams.
const SEED_BASE: i32 = 100_003;
const SEED_STRIDE: i32 = 7_919;

/// A fault fixture and its subfault count, for labelling.
#[derive(Clone, Copy, Debug)]
pub struct Fault {
    pub name: &'static str,
    pub stoch: &'static str,
    pub subfaults: usize,
}

pub const MINI: Fault = Fault { name: "mini", stoch: "2012p578973", subfaults: 4 };
pub const MEDIUM: Fault = Fault { name: "medium", stoch: "2013p543824", subfaults: 112 };
pub const ALPINE: Fault =
    Fault { name: "alpine", stoch: "alpine_base_r1", subfaults: 2827 };

/// One stratum: a fault at a station offset, with a record long enough to hold
/// the arrival.
#[derive(Clone, Debug)]
pub struct Stratum {
    pub fault: Fault,
    /// Station offset in degrees of longitude from the fault reference point.
    pub dlon: f64,
    /// Record length, seconds.
    pub duration: f64,
    /// Measured `d10` for this offset, km — a label, confirmed against the
    /// binary's stderr at run time.
    pub nominal_km: f64,
}

/// The distance ladder: offsets and record lengths, measured rather than derived.
///
/// Two things make this less obvious than "convert km to degrees":
///
/// 1. **There is a floor on distance.** `d10` is the closest *subfault* distance,
///    which includes source depth. The mini fault's top is at 25.63 km, so no
///    station offset can produce `d10` below about 27 km. Targeting 5 or 15 km
///    silently gives 27 km instead.
///
/// 2. **The record must be long enough to contain the S arrival.** At `d10` km the
///    arrival is roughly `d10 / 3.5` seconds, so a 20 s record holds nothing
///    beyond about 50 km — the accumulation window starts past `ndata` and the
///    output is *exactly zero*, not merely small. A 100 s record covers the whole
///    ladder, and costs only 20-35 ms per run.
///
/// The offsets below were chosen by measuring the resulting `d10` and picking
/// values that straddle the `ipdur_model = 11` path-duration breakpoints at 45 and
/// 125 km. The 7 km breakpoint is unreachable for this fault (see 1) and the
/// 175 km one is past where a 4-subfault fault has useful amplitude.
const LADDER: &[(f64, f64, f64)] = &[
    // (dlon, duration, measured d10)
    (0.0568, 100.0, 26.8),  // closest attainable; source depth dominates
    (0.4545, 100.0, 48.1),  // just past the 45 km breakpoint
    (0.9091, 100.0, 84.6),
    (1.4773, 100.0, 133.2), // just past the 125 km breakpoint
    (1.7045, 100.0, 152.9),
];

pub fn distance_ladder(fault: Fault, n: usize) -> Vec<Stratum> {
    LADDER
        .iter()
        .take(n)
        .map(|&(dlon, duration, km)| Stratum { fault, dlon, duration, nominal_km: km })
        .collect()
}

/// The fixed seed list.
pub fn seeds(n: usize) -> Vec<i32> {
    (0..n)
        .map(|i| SEED_BASE.wrapping_add(SEED_STRIDE.wrapping_mul(i as i32)))
        .collect()
}

/// A deck with the seed and output path left to be substituted per run.
///
/// Generated by `harness/mkdeck.py`, which stays the single source of truth for
/// the deck format — the benchmarks and the parity gate use it too, so they
/// cannot drift apart in what they consider a production deck. Calling it once
/// per stratum rather than once per run keeps the Python cost negligible.
pub struct DeckTemplate {
    lines: Vec<String>,
}

/// Line indices in the 22-line production deck. Substituting by index rather than
/// by pattern because the values are bare numbers and paths with no distinguishing
/// syntax — a sentinel could collide with a real value.
const LINE_OUTPUT: usize = 3;
const LINE_SEED: usize = 7;

impl DeckTemplate {
    pub fn build(root: &Path, st: &Stratum, station_file: &Path) -> std::io::Result<Self> {
        let out = Command::new("python3")
            .arg(root.join("harness/mkdeck.py"))
            .arg("--stoch")
            .arg(root.join(format!("harness/fixtures/stoch/{}.stoch", st.fault.stoch)))
            .arg("--velmod")
            .arg(root.join("harness/fixtures/velocity_model"))
            .arg("--station-file")
            .arg(station_file)
            .arg("--output-file")
            .arg("PLACEHOLDER")
            .arg("--dlon")
            .arg(format!("{}", st.dlon))
            .arg("--duration")
            .arg(format!("{}", st.duration))
            .arg("--write-station")
            .output()?;
        if !out.status.success() {
            return Err(std::io::Error::other(format!(
                "mkdeck.py failed: {}",
                String::from_utf8_lossy(&out.stderr)
            )));
        }
        let lines: Vec<String> =
            String::from_utf8_lossy(&out.stdout).lines().map(|s| s.to_string()).collect();
        assert!(
            lines.len() >= LINE_SEED + 1,
            "deck has {} lines, too short to substitute",
            lines.len()
        );
        Ok(Self { lines })
    }

    pub fn with(&self, seed: i32, output: &Path) -> String {
        let mut l = self.lines.clone();
        l[LINE_OUTPUT] = output.display().to_string();
        l[LINE_SEED] = seed.to_string();
        let mut s = l.join("\n");
        s.push('\n');
        s
    }
}

/// One realisation's measurements.
#[derive(Clone, Debug)]
pub struct Realisation {
    pub seed: i32,
    /// Epicentral distance the binary reported on stderr, km.
    pub reported_km: f64,
    /// Per component: 090, 000, ver.
    pub measures: [Measures; 3],
    /// Log FAS per component, binned. `None` for bands with no bin.
    pub log_fas: [Vec<Option<f64>>; 3],
}

/// Run one binary once and measure the result.
pub fn run_one(
    exe: &Path,
    deck: &str,
    output: &Path,
    dt: f64,
    fas_edges: &[f64],
) -> std::io::Result<(f64, [Measures; 3], [Vec<Option<f64>>; 3])> {
    // The Fortran opens its output without truncation and seeks to byte 0, so a
    // stale longer file would leave trailing bytes from a previous run.
    let _ = std::fs::remove_file(output);

    let mut child = Command::new(exe)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()?;
    child.stdin.as_mut().expect("stdin").write_all(deck.as_bytes())?;
    let out = child.wait_with_output()?;
    if !out.status.success() {
        return Err(std::io::Error::other(format!(
            "{} exited with {}: {}",
            exe.display(),
            out.status,
            String::from_utf8_lossy(&out.stderr)
        )));
    }
    // stderr carries one `(1x,f10.4)` epicentral distance per station.
    let reported_km: f64 = String::from_utf8_lossy(&out.stderr)
        .split_whitespace()
        .next()
        .and_then(|s| s.parse().ok())
        .unwrap_or(f64::NAN);

    let raw = im::read_output(output)?;
    let comps = im::split_components(&raw);
    let measures = [
        Measures::compute(&comps[0], dt),
        Measures::compute(&comps[1], dt),
        Measures::compute(&comps[2], dt),
    ];
    let log_fas = [
        log_binned(&comps[0], dt, fas_edges),
        log_binned(&comps[1], dt, fas_edges),
        log_binned(&comps[2], dt, fas_edges),
    ];
    Ok((reported_km, measures, log_fas))
}

fn log_binned(acc: &[f32], dt: f64, edges: &[f64]) -> Vec<Option<f64>> {
    im::fas::fas_binned(acc, dt, edges)
        .into_iter()
        .map(|o| o.map(|v| v.ln()))
        .collect()
}

/// Everything measured for one binary over one stratum.
pub struct StratumResult {
    pub stratum: Stratum,
    pub realisations: Vec<Realisation>,
}

impl StratumResult {
    /// Reject a stratum that carries no signal.
    ///
    /// If the record is shorter than the S arrival the output is exactly zero, and
    /// every IM then comes out as zero or NaN. That is a *configuration* error, and
    /// reporting it as "not equivalent" would be actively misleading — two
    /// simulators agreeing that the answer is nothing is not a finding.
    pub fn check_has_signal(&self) -> Result<(), String> {
        for (ci, cname) in im::COMPONENTS.iter().enumerate() {
            let peak = self
                .realisations
                .iter()
                .map(|r| r.measures[ci].pga)
                .fold(0.0f64, f64::max);
            if !(peak > 0.0) {
                return Err(format!(
                    "stratum {}@{:.0}km component {cname} has zero amplitude in all {} \
                     realisations. The record ({} s) is almost certainly shorter than the \
                     S arrival at this distance, so there is nothing to compare.",
                    self.stratum.fault.name,
                    self.stratum.nominal_km,
                    self.realisations.len(),
                    self.stratum.duration
                ));
            }
        }
        Ok(())
    }

    /// Values of one endpoint across realisations, for one component.
    pub fn endpoint(&self, comp: usize, name: &str) -> Vec<f64> {
        self.realisations
            .iter()
            .filter_map(|r| {
                r.measures[comp]
                    .endpoints()
                    .into_iter()
                    .find(|(n, _)| n == name)
                    .map(|(_, v)| v)
            })
            .collect()
    }

    /// Log-FAS matrix `[realisation][band]`, dropping bands that are empty in any
    /// realisation so the correlation matrix has no holes.
    pub fn fas_matrix(&self, comp: usize) -> (Vec<usize>, Vec<Vec<f64>>) {
        let nb = self.realisations.first().map_or(0, |r| r.log_fas[comp].len());
        let keep: Vec<usize> = (0..nb)
            .filter(|&b| self.realisations.iter().all(|r| r.log_fas[comp][b].is_some()))
            .collect();
        let rows = self
            .realisations
            .iter()
            .map(|r| keep.iter().map(|&b| r.log_fas[comp][b].unwrap()).collect())
            .collect();
        (keep, rows)
    }
}

/// Scratch paths, one set per worker thread so parallel runs cannot collide.
pub struct Workspace {
    pub dir: PathBuf,
}

impl Workspace {
    pub fn new(root: &Path, tag: &str) -> std::io::Result<Self> {
        let dir = root.join("harness/out/validate").join(tag);
        std::fs::create_dir_all(&dir)?;
        Ok(Self { dir })
    }
    pub fn station(&self) -> PathBuf {
        self.dir.join("station.ll")
    }
    pub fn output(&self, tag: &str) -> PathBuf {
        self.dir.join(format!("{tag}.bin"))
    }
}
